# Generated by Django 4.2.7 on 2024-01-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='admin', max_length=64, verbose_name='Name')),
                ('email', models.EmailField(default='bond007@gmail.com', max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=254, verbose_name='Subject')),
                ('message', models.CharField(max_length=254, verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Buy')),
                ('sell', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Sell')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('type', models.SmallIntegerField(choices=[(1, 'Dollar_USA'), (2, 'EVRO_Europe'), (3, 'Ukrainian_hryvnia'), (4, 'Polish_zloty')], default=1, verbose_name='Type')),
                ('source', models.CharField(choices=[('PIVDENNY', 'Bank Pivdenny'), ('PRIVAT', 'Bank PRIVAT'), ('CREDITDNEPR', 'Bank Credit Dnipro'), ('MONOBANK', 'Bank MONO')], default='PRIVAT', max_length=255, verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Rate',
                'verbose_name_plural': 'Rates',
            },
        ),
        migrations.CreateModel(
            name='RequestResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=256, verbose_name='Path')),
                ('request_method', models.CharField(max_length=256, verbose_name='Request method')),
                ('time', models.FloatField(verbose_name='Time')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(choices=[('https://bank.com.ua/en', 'Bank Pivdenny'), ('https://api.privatbank.ua/p24api/pubinfo?exchange&coursid=5', 'Bank PRIVAT'), ('https://creditdnepr.com.ua/en', 'Bank Credit Dnipro'), ('https://api.monobank.ua/bank/currency', 'Bank MONO')], max_length=255, verbose_name='Source URL')),
                ('source_name', models.CharField(choices=[('PIVDENNY', 'Bank Pivdenny'), ('PRIVAT', 'Bank PRIVAT'), ('CREDITDNEPR', 'Bank Credit Dnipro'), ('MONOBANK', 'Bank MONO')], default='PRIVAT', max_length=64, verbose_name='Source name')),
                ('code_name', models.CharField(max_length=64, unique=True, verbose_name='Code name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('logo', models.FileField(blank=True, default=None, null=True, upload_to='logo/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
            },
        ),
    ]
