# Generated by Django 4.2.7 on 2023-12-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField(verbose_name='subject')),
                ('message', models.TextField(verbose_name='message')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sell', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('type', models.SmallIntegerField(choices=[(1, 'Dollar_USA'), (2, 'EVRO_Europe'), (3, 'Ukrainian_hryvnia'), (4, 'Polish_zloty')], default=1)),
                ('source', models.CharField(choices=[('PIVDENNY', 'Bank Pivdenny'), ('PRIVAT', 'Bank PRIVAT'), ('CREDITDNEPR', 'Bank Credit Dnipro')], default='PRIVAT', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(choices=[('https://bank.com.ua/en', 'Bank Pivdenny'), ('https://en.privatbank.ua/', 'Bank PRIVAT'), ('https://creditdnepr.com.ua/en', 'Bank Credit Dnipro')], max_length=255)),
                ('source_name', models.CharField(choices=[('PIVDENNY', 'Bank Pivdenny'), ('PRIVAT', 'Bank PRIVAT'), ('CREDITDNEPR', 'Bank Credit Dnipro')], default='PRIVAT', max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
