# Generated by Django 4.2.7 on 2024-01-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='source',
            field=models.CharField(choices=[('PIVDENNY', 'Bank Pivdenny'), ('PRIVAT', 'Bank PRIVAT'), ('CREDITDNEPR', 'Bank Credit Dnipro'), ('MONOBANK', 'Bank MONO')], default='PRIVAT', max_length=255, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_name',
            field=models.CharField(choices=[('PIVDENNY', 'Bank Pivdenny'), ('PRIVAT', 'Bank PRIVAT'), ('CREDITDNEPR', 'Bank Credit Dnipro'), ('MONOBANK', 'Bank MONO')], default='PRIVAT', max_length=64, verbose_name='Source name'),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_url',
            field=models.URLField(choices=[('https://bank.com.ua/en', 'Bank Pivdenny'), ('https://en.privatbank.ua/', 'Bank PRIVAT'), ('https://creditdnepr.com.ua/en', 'Bank Credit Dnipro'), ('https://www.monobank.ua/', 'Bank MONO')], max_length=255, verbose_name='Source URL'),
        ),
    ]
