# Generated by Django 4.2.7 on 2024-01-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_alter_rate_source_alter_source_source_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_url',
            field=models.URLField(choices=[('https://bank.com.ua/en', 'Bank Pivdenny'), ('https://api.privatbank.ua/p24api/pubinfo?exchange&coursid=5', 'Bank PRIVAT'), ('https://creditdnepr.com.ua/en', 'Bank Credit Dnipro'), ('https://api.monobank.ua/bank/currency', 'Bank MONO')], max_length=255, verbose_name='Source URL'),
        ),
    ]
