# Generated by Django 4.2.7 on 2023-12-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_alter_contactus_options_alter_rate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='source',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_name',
            field=models.CharField(choices=[('PIVDENNY', 'Bank Pivdenny'), ('PRIVAT', 'Bank PRIVAT'), ('CREDITDNEPR', 'Bank Credit Dnipro')], default='PRIVAT', max_length=64, verbose_name='Source name'),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_url',
            field=models.URLField(choices=[('https://bank.com.ua/en', 'Bank Pivdenny'), ('https://en.privatbank.ua/', 'Bank PRIVAT'), ('https://creditdnepr.com.ua/en', 'Bank Credit Dnipro')], max_length=255, verbose_name='Source URL'),
        ),
    ]
