# Generated by Django 4.2.7 on 2023-12-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_contactus_name_alter_contactus_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.CharField(max_length=254, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(max_length=254, verbose_name='Subject'),
        ),
    ]
