# Generated by Django 4.2.7 on 2023-12-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_requestresponselog'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='logo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='Logo'),
        ),
    ]
